### ISSUE TITLE
Support for OPUS_FRAMESIZE_ARG

### ISSUE THREAD

**Issue by maestroIgor** [xiph/libopusenc#22]
Why it is not possible to explicitly set frame duration to default (OPUS_FRAMESIZE_ARG) 

`ope_encoder_ctl(encoder_.get(), OPUS_SET_EXPERT_FRAME_DURATION(static_cast<opus_int32>(frameSize)));`

Probably method ope_encoder_ctl() has an inconsistant check: 
```cpp
    case OPUS_SET_EXPERT_FRAME_DURATION_REQUEST:
    {
      opus_int32 value = va_arg(ap, opus_int32);
      int max_supported = OPUS_FRAMESIZE_60_MS;
#ifdef OPUS_FRAMESIZE_120_MS
      max_supported = OPUS_FRAMESIZE_120_MS;
#endif
      if (value < OPUS_FRAMESIZE_2_5_MS || value > max_supported) {
        ret = OPUS_UNIMPLEMENTED;
        break;
      }
      ret = opeint_encoder_ctl(&enc->st, OPUS_SET_EXPERT_FRAME_DURATION(value));
      if (ret == OPUS_OK) {
        enc->frame_size = compute_frame_samples(value);
        enc->frame_size_request = value;
      }
    }```

**Comment by mark4o** [comment]
In libopus, each call to opus_encode() takes PCM samples as input and produces exactly one Opus packet as output.  OPUS_FRAMESIZE_ARG (the libopus default) means that the duration of the packet that you get back is taken from the number of PCM samples provided as input; only a few sample rates are supported and the number of samples that you provide to opus_encode() has to correspond to one of the valid packet sizes.  For example if the sample rate is 48 kHz mono and you call opus_encode() with 480 PCM samples (10 ms) it will return an Opus packet containing one 10 ms frame.

libopusenc supports arbitrary sample rates and delayed decision (where the encoder may look ahead a couple of seconds in order to make better encoding decisions).  Instead of getting back one packet for each call, that you would need to write to the file yourself, you can call ope_encoder_write() with as many PCM samples as you want at whatever sample rate you want and it will take care of generating and writing the packets whenever it has buffered enough samples for another packet.  Due to delayed decision it may write no audio packets at all until you have written a couple seconds of PCM samples.  On the other hand if you give it a lot of audio at once it may write multiple packets from a single call to ope_encoder_write().  Since it does not operate on a one-packet-per-call model, OPUS_FRAMESIZE_ARG does not make sense for libopusenc.

In libopusenc the default is OPUS_FRAMESIZE_20_MS.  You can call ope_encoder_write() with an arbitrary number of PCM samples at a time, or even the whole stream in one call, and it will write an Opus packet for each 20 ms of audio.  You do not need to break it up into frame-size chunks; that is handled by libopusenc.

**Comment by maestroIgor** [comment]
Thank you for the quick response! I got the idea
